# backend/Dockerfile

FROM python:3.9-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /backend

COPY requirements.txt /backend/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /backend/
COPY start.sh /backend/

RUN chmod +x /backend/start.sh

CMD ["/bin/bash", "/backend/start.sh"]

